

  -- INSERT
  INSERT INTO TSTUDENTS (S_NAME,S_HEIGHT) value ("abc",177.0);
  INSERT INTO TSTUDENTS (S_NAME,S_HEIGHT) value ("bcd",134.0);
  INSERT INTO TSTUDENTS (S_NAME,S_HEIGHT) value ("ccc",179.0);
	INSERT INTO TSTUDENTS (S_NAME,S_HEIGHT) value ("Ge",122.4);
  

  COMMIT; --ROLLBACK
