server:
  port: 8099

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/sys
  username: root
  password: Ommg_102899
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true
  

spring:
  sql:
    init:
      schema-locations: classpath:DDL_AUTHORS.sql,classpath:DDL_BOOKS.sql
      data-locations: classpath:DML_AUTHORS.sql,classpath:DML_BOOKS.sql
      mode: always

rest:
  greeting:
    baseUrl: http://localhost:8011
    serviceVers: api/v1
    serviceUrl: greeting

  
